// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvbgiwowvbdiqggvumkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Ymdpd293dmJkaXFnZ3Z1bWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTc4ODMsImV4cCI6MjA2NjM5Mzg4M30.PflhZTJfax5f_NgpUVqFUaOKT-3gaejqoqFKWT2I37Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);